// Mocks generated by Mockito 5.4.6 from annotations
// in food_resturant_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:food_resturant_app/data/datasources/remote/api_client.dart'
    as _i3;
import 'package:food_resturant_app/data/models/banners/banner_item.dart' as _i6;
import 'package:food_resturant_app/data/models/base_response.dart' as _i2;
import 'package:food_resturant_app/data/models/campaigns/campaigns_item.dart'
    as _i9;
import 'package:food_resturant_app/data/models/categories/categories.dart'
    as _i7;
import 'package:food_resturant_app/data/models/configurations/configuration_model.dart'
    as _i5;
import 'package:food_resturant_app/data/models/popular_products/popular_products.dart'
    as _i8;
import 'package:food_resturant_app/data/models/resturants/resturants_item.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBaseResponse_0<T> extends _i1.SmartFake
    implements _i2.BaseResponse<T> {
  _FakeBaseResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseResponse<_i5.Configuration>> getConfiguration() =>
      (super.noSuchMethod(
            Invocation.method(#getConfiguration, []),
            returnValue: _i4.Future<_i2.BaseResponse<_i5.Configuration>>.value(
              _FakeBaseResponse_0<_i5.Configuration>(
                this,
                Invocation.method(#getConfiguration, []),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponse<_i5.Configuration>>);

  @override
  _i4.Future<_i2.BaseResponse<_i6.BannerItem>> getBanners() =>
      (super.noSuchMethod(
            Invocation.method(#getBanners, []),
            returnValue: _i4.Future<_i2.BaseResponse<_i6.BannerItem>>.value(
              _FakeBaseResponse_0<_i6.BannerItem>(
                this,
                Invocation.method(#getBanners, []),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponse<_i6.BannerItem>>);

  @override
  _i4.Future<_i2.BaseResponse<List<_i7.Categories>>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i4.Future<_i2.BaseResponse<List<_i7.Categories>>>.value(
                  _FakeBaseResponse_0<List<_i7.Categories>>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i4.Future<_i2.BaseResponse<List<_i7.Categories>>>);

  @override
  _i4.Future<_i2.BaseResponse<_i8.PopularProducts>> getProductPopular() =>
      (super.noSuchMethod(
            Invocation.method(#getProductPopular, []),
            returnValue:
                _i4.Future<_i2.BaseResponse<_i8.PopularProducts>>.value(
                  _FakeBaseResponse_0<_i8.PopularProducts>(
                    this,
                    Invocation.method(#getProductPopular, []),
                  ),
                ),
          )
          as _i4.Future<_i2.BaseResponse<_i8.PopularProducts>>);

  @override
  _i4.Future<_i2.BaseResponse<_i9.CampaignsItem>> getCampaignsItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCampaignsItems, []),
            returnValue: _i4.Future<_i2.BaseResponse<_i9.CampaignsItem>>.value(
              _FakeBaseResponse_0<_i9.CampaignsItem>(
                this,
                Invocation.method(#getCampaignsItems, []),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponse<_i9.CampaignsItem>>);

  @override
  _i4.Future<_i2.BaseResponse<_i10.ResturantItem>> getResturantItems({
    int? offset,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getResturantItems, [], {
              #offset: offset,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.BaseResponse<_i10.ResturantItem>>.value(
              _FakeBaseResponse_0<_i10.ResturantItem>(
                this,
                Invocation.method(#getResturantItems, [], {
                  #offset: offset,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.BaseResponse<_i10.ResturantItem>>);
}
